Repository ajaynegi45/LibraryMan-API, pull requests merged in 2024-10, with the labels that each got.

#63 Fix optimizing db calls (#24)
  api-docs/borrowings-api.md
  src/main/java/com/libraryman_api/borrowing/BorrowingService.java
  src/main/java/com/libraryman_api/member/MemberService.java
  src/main/java/com/libraryman_api/notification/NotificationService.java
  src/main/resources/application.properties
Labels: hacktoberfest-accepted, hacktoberfest, status: ready for dev, gssoc, gssoc-ext, level3

#71 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#78 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yml
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, gssoc, gssoc-ext, level2
